name: Test Django CI

on:
  push:
    branches: [feature/addd_users]
  pull-request:
    branches: [featute/add_users, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkpot@v2

      -name: Set up Python 3.10
       uses: actions/setup-python@v4
       with:
         python-version: "3.10"

