name: Test Django CI

on:
  push:
    branches: [feature/add_users]
  pull_request:
    branches: [feature/add_users, main]


jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Set up .env
          run: |
            echo "${{secrets.ENV_FILE}}" > test_site/.env
        - name: Run DB
          run: |
            docker-compose -f test_site/docker-compose.yml up -d db 
        - name: Wait for DB
          run: |
            until docker exec -t $(docker ps -q -f name=shop_db_1) pg_ready -h localhost -p 5432; do
              echo "Waiting for database to be ready...";
              sleep 5;
            done
        - name : Install Dependencies
          run : |
            python -m pip install --upgrade pip
            pip install -r test_site/requirements.txt
